project:
  type: website
  output-dir: docs


website:
  title: "Muller"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/jtmuller5
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: solar
    css: styles.css



